timeout: "1200s"
options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PIPELINE_TYPE: "android"
  _WEBHOOK_URL: "https://webhook.site/your-unique-id"

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "Android CI/CD Build Triggered!"
        echo "Build ID: $$BUILD_ID"
        echo "Project: $$PROJECT_ID"
        echo "Pipeline Type: $$_PIPELINE_TYPE"
        echo "Webhook URL: $$_WEBHOOK_URL"

        echo "Available source files:"
        gsutil ls gs://rounds-android-cicd-source-uploads/ || echo "No source files found"

        echo "Build completed at $$(date)" > /workspace/build_info.txt
        gsutil cp /workspace/build_info.txt gs://rounds-android-cicd-build-artifacts/$$BUILD_ID/
        echo "Build artifacts uploaded to: gs://rounds-android-cicd-build-artifacts/$$BUILD_ID/"
